version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ticketing-postgres
    environment:
      POSTGRES_DB: ticketing_db
      POSTGRES_USER: ticketing_user
      POSTGRES_PASSWORD: ticketing_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticketing-network

  backend:
    build: ./backend
    container_name: ticketing-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ticketing_db
      SPRING_DATASOURCE_USERNAME: ticketing_user
      SPRING_DATASOURCE_PASSWORD: ticketing_password
      JWT_SECRET: mySecretKey
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - ticketing-network

  frontend:
    build: ./frontend
    container_name: ticketing-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ticketing-network

volumes:
  postgres_data:

networks:
  ticketing-network:
    driver: bridge