spring:
  application:
    name: ticketing
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketing
    username: ticket
    password: ticket
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
