spring:
  application:
    name: ticketing-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketing_db
    username: ticketing_user
    password: ticketing_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:mySecretKey}
    expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    com.ticketing.backend: DEBUG
    org.springframework.security: DEBUG